esphome:
  name: ccs811-testing
  platformio_options:
    platform: https://github.com/lucaskatayama/platform-espressif32.git#feat/seeed_xiao_esp32c6.json
    #platform: https://github.com/lucaskatayama/platform-espressif32.git#lp_i2c

esp32:
  board: seeed_xiao_esp32c6
  variant: ESP32C6
  framework:
    type: esp-idf
    version: 5.3.0
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

logger:
  baud_rate: 115200
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  frequency: 150kHz

sensor:
  - platform: bmp280_i2c
    id: bmp280_sensor
    temperature:
      name: 'Temperature (BMP280)'
      id: bmp280_temp
    pressure:
      name: 'Pressure'
      id: bmp280_press
    address: 0x76
    update_interval: 1s

  - platform: htu21d
    id: si7021_sensor
    temperature:
      name: 'Temperature (Si7021)'
      id: si7021_temp
    humidity:
      name: 'Humidity'
      id: si7021_hum
    address: 0x40
    update_interval: 1s
  - platform: ccs811
    id: ccs811_sensor
    eco2:
      name: 'CCS811 eCO2 Value'
      id: ccs811_eco2
      on_value:
        logger.log:
          level: INFO
          format: 'CCS811 eCO2 Value: %.2f'
          args: [x]
    tvoc:
      name: 'CCS811 Total Volatile Organic Compound'
      id: ccs811_tvoc
      on_value:
        logger.log:
          level: INFO
          format: 'CCS811 TVOC Value: %.2f'
          args: [x]
    temperature: bmp280_temp
    humidity: si7021_hum
    address: 0x5A
    update_interval: 10s
    baseline: 0xFDC0
