esphome:
  name: esp32-transmitter
  platform: ESP32
  board: esp32-c3-devkitm-1

external_components:
  - source:
      type: git
      url: https://github.com/nielsnl68/esphome
      ref: 'nvds-new-espnow'
    components: [espnow]

logger:

espnow:
  auto_add_peer: false
  wifi_channel: 1
  peers:
    - FF:FF:FF:FF:FF:FF
# Own Peer Address (MAC Address) from log
# [C][logger:185]: Logger:
# [C][logger:186]:   Level: DEBUG
# [C][logger:188]:   Log Baud Rate: 115200
# [C][logger:189]:   Hardware UART: USB_CDC
# [C][espnow:037]: esp_now:
# [C][espnow:039]:   Own Peer Address: 0xe4d8931d0470.
# [C][espnow:040]:   Wifi channel: 1.
# [C][espnow:041]:   Auto add new peers: No.
# [C][espnow:043]:   Use sent status: Yes.
# [C][espnow:044]:   Conversation timeout: 1388ms.
# [C][espnow:045]:   Send retries: 5.
