esphome:
  name: 290test2
  friendly_name: 290test2

  on_boot:
    priority: -1000
    then:
      - script.execute: my_script
spi:

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source: components
    components:
      - vision_master
    refresh: 1min

vision_master:
  id: my_display

# Enable logging
logger:
  baud_rate: 115200
  level: VERBOSE

script:
  id: my_script
  then:
    - lambda: |-
        id(my_display).clearMemory(); // Start a new drawing
    - delay: 4s
    - lambda: |-
        id(my_display).landscape();
        id(my_display).setFont(&FreeSans9pt7b);
        id(my_display).printCenter("It works from boot!");
        id(my_display).update();
    - delay: 10s
    - lambda: |-
        id(my_display).clearMemory(); // Start a new drawing
        id(my_display).clear(); // Physically clear the screen

# interval:
#   - startup_delay: 5s
#     interval: 10s
#     then:
#       - script.execute: my_script
