esphome:
  name: 290test2
  friendly_name: 290test2

spi:

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source: components
    components:
      - vision_master
    refresh: 1min

vision_master:
  id: my_display

# Enable logging
logger:
  baud_rate: 115200
  level: VERBOSE
# interval:
#   - startup_delay: 5s
#     interval: 10s
#     then:
#       - logger.log: 'Displaying'
#       - lambda: |-
