esphome:
  name: esp32-modbus
  platform: ESP32
  board: esp32-c3-devkitm-1

logger:

# wifi:
#   ssid: !secret WiFi_ssid
#   password: !secret WiFi_password

external_components:
  - source:
      type: git
      url: https://github.com/nielsnl68/esphome
      ref: "nvds-new-espnow"
    components: [ espnow ]

# api:
#   password: !secret API_password

# ota:
#   - platform: esphome
#     password: !secret OTA_password

uart:
  - id: intmodbus
    tx_pin: 21
    rx_pin: 20
    baud_rate: 4800
    stop_bits: 1
    data_bits: 8
    parity: NONE
    debug:
      direction: BOTH

modbus:
  flow_control_pin: GPIO1
  id: modbus1

modbus_controller:
  - id: modbus_device
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    update_interval: never  # Do not poll sensor automatically

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: 'Humidity'
    register_type: holding
    address: 0x00
    unit_of_measurement: '%RH'
    value_type: U_WORD
    id: 'humidity'
    accuracy_decimals: 1
    filters:
      - multiply: 0.1


espnow:
  auto_add_peer: true
  wifi_channel: "11"
  peers:
    - 70:04:1D:93:0B:78
    - FF:FF:FF:FF:FF:FF

interval:
  - interval: 1s
    then:
      - component.update: modbus_device
      - delay: 1s
      - espnow.send:
          data: !lambda |-
            char buffer[10];
            snprintf(buffer, sizeof(buffer), "%.1f", id(humidity).state);
            return std::vector<unsigned char>(buffer, buffer + strlen(buffer));