esphome:
  name: esp32-modbus
  platform: ESP32
  board: esp32-c3-devkitm-1
  
logger:

# wifi:
#   ssid: !secret WiFi_ssid
#   password: !secret WiFi_password

# api:
#   password: !secret API_password

# ota:
#   - platform: esphome
#     password: !secret OTA_password

external_components:
  - source:
      type: git
      url: https://github.com/nielsnl68/esphome
      ref: "nvds-new-espnow"
    components: [ espnow ]

uart:
  - id: intmodbus
    tx_pin: 21
    rx_pin: 20
    baud_rate: 4800
    stop_bits: 1
    data_bits: 8
    parity: NONE
    debug:
      direction: BOTH

modbus:
  flow_control_pin: GPIO1
  id: modbus1

modbus_controller:
  - id: modbus_device
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    update_interval: never  # Do not poll sensor automatically

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: 'Humidity'
    register_type: holding
    address: 0x00
    unit_of_measurement: '%RH'
    value_type: U_WORD
    id: 'humidity'
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Temperature"
    register_type: holding
    address: 0x01  # Register for temperature
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1  # Apply scaling as per the manual
    id: 'temperature'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Conductivity"
    register_type: holding
    address: 0x02  # Register for conductivity
    unit_of_measurement: "µS/cm"
    value_type: U_WORD
    accuracy_decimals: 0
    filters:
      - multiply: 1.0  # No scaling needed
    id: 'conductivity'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "pH"
    register_type: holding
    address: 0x03  # Register for pH
    unit_of_measurement: "pH"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1  # Scaling factor for pH
    id: 'ph'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Nitrogen (N)"
    register_type: holding
    address: 0x04  # Register for Nitrogen
    unit_of_measurement: "mg/kg"
    value_type: U_WORD
    accuracy_decimals: 0
    filters:
      - multiply: 1.0  # No scaling needed
    id: 'nitrogen'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Phosphorus (P)"
    register_type: holding
    address: 0x05  # Register for Phosphorus
    unit_of_measurement: "mg/kg"
    value_type: U_WORD
    accuracy_decimals: 0
    filters:
      - multiply: 1.0  # No scaling needed
    id: 'phosphorus'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Potassium (K)"
    register_type: holding
    address: 0x06  # Register for Potassium
    unit_of_measurement: "mg/kg"
    value_type: U_WORD
    accuracy_decimals: 0
    filters:
      - multiply: 1.0  # No scaling needed
    id: 'potassium'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Salinity"
    register_type: holding
    address: 0x07  # Register for salinity
    unit_of_measurement: "mg/L"
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'salinity'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "TDS"
    register_type: holding
    address: 0x08  # Register for TDS
    unit_of_measurement: "mg/L"
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'tds'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Conductivity Factor"
    register_type: holding
    address: 0x22  # Register for conductivity factor
    unit_of_measurement: "x"
    value_type: U_WORD
    id: 'cond_f'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Salinity Factor"
    register_type: holding
    address: 0x23  # Register for salinity factor
    unit_of_measurement: "x"
    value_type: U_WORD
    id: 'sal_f'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "TDS Factor"
    register_type: holding
    address: 0x24  # Register for TDS factor
    unit_of_measurement: "x"
    value_type: U_WORD
    id: 'tds_f'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Temperature Offset"
    register_type: holding
    address: 0x50  # Register for temperature offset
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1  # Scaling factor for offset
    id: 'temp_offset'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Humidity Offset"
    register_type: holding
    address: 0x51  # Register for humidity offset
    unit_of_measurement: "%RH"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1  # Scaling factor for offset
    id: 'hum_offset'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Conductivity Offset"
    register_type: holding
    address: 0x52  # Register for conductivity offset
    unit_of_measurement: "µS/cm"
    value_type: U_WORD
    accuracy_decimals: 0
    filters:
      - multiply: 1.0  # No scaling needed
    id: 'cond_offset'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "pH Offset"
    register_type: holding
    address: 0x53  # Register for pH offset
    unit_of_measurement: "pH"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1  # Scaling factor for pH offset
    id: 'ph_offset'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Nitrogen Factor High"
    register_type: holding
    address: 0x4E8  # Nitrogen factor high byte
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'n_f_high'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Nitrogen Factor Low"
    register_type: holding
    address: 0x4E9  # Nitrogen factor low byte
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'n_f_low'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Nitrogen Offset"
    register_type: holding
    address: 0x4EA  # Nitrogen offset
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'n_offset'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Phosphorus Factor High"
    register_type: holding
    address: 0x4F2  # Phosphorus factor high byte
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'p_f_high'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Phosphorus Factor Low"
    register_type: holding
    address: 0x4F3  # Phosphorus factor low byte
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'p_f_low'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Phosphorus Offset"
    register_type: holding
    address: 0x4F4  # Phosphorus offset
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'p_offset'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Potassium Factor High"
    register_type: holding
    address: 0x4FC  # Potassium factor high byte
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'k_f_high'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Potassium Factor Low"
    register_type: holding
    address: 0x4FD  # Potassium factor low byte
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'k_f_low'

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Potassium Offset"
    register_type: holding
    address: 0x4FE  # Potassium offset
    value_type: U_WORD
    accuracy_decimals: 0
    id: 'k_offset'

espnow:
  auto_add_peer: true
  wifi_channel: "11"
  peers:
    - FF:FF:FF:FF:FF:FF
  on_receive:
    then:
      - lambda: |-
          ESP_LOGI("main", "Received data from ESP-NOW");

          // Convert the received data to a string
          std::string received_string((char*)packet.get_payload(), packet.size);
          
          ESP_LOGI("main", "Received data: %s", received_string.c_str());

          if (received_string == "getcalibration") {
            ESP_LOGI("main", "Calibration data requested");
            id(get_calibration) = true;
          }
      - if:
          condition:
            lambda: 'return id(get_calibration);'  
          then:
            - component.update: modbus_device
            - delay: 5s
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;cond_f;%.0f", id(device_id).c_str(), id(cond_f).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;sal_f;%.0f", id(device_id).c_str(), id(sal_f).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;tds_f;%.0f", id(device_id).c_str(), id(tds_f).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;temp_offset;%.1f", id(device_id).c_str(), id(temp_offset).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;hum_offset;%.1f", id(device_id).c_str(), id(hum_offset).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;cond_offset;%.0f", id(device_id).c_str(), id(cond_offset).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;ph_offset;%.1f", id(device_id).c_str(), id(ph_offset).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;n_f_high;%.0f", id(device_id).c_str(), id(n_f_high).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;n_f_low;%.0f", id(device_id).c_str(), id(n_f_low).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;n_offset;%.0f", id(device_id).c_str(), id(n_offset).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;p_f_high;%.0f", id(device_id).c_str(), id(p_f_high).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;p_f_low;%.0f", id(device_id).c_str(), id(p_f_low).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;p_offset;%.0f", id(device_id).c_str(), id(p_offset).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;k_f_high;%.0f", id(device_id).c_str(), id(k_f_high).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;k_f_low;%.0f", id(device_id).c_str(), id(k_f_low).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - delay: 500ms
            - espnow.send:
                data: !lambda |-
                  char buffer[30];
                  snprintf(buffer, sizeof(buffer), "%s;k_offset;%.0f", id(device_id).c_str(), id(k_offset).state);
                  return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
            - lambda: |- 
                ESP_LOGI("main", "Calibration data sent");
                id(get_calibration) = false;
          else:
            - lambda: |-
                ESP_LOGI("main", "Calibration data not requested");

globals:
  - id: device_id
    type: std::string
    initial_value: '"01"'
  - id: get_calibration
    type: bool
    initial_value: 'false'

interval:
  - interval: 10s
    then:
      - component.update: modbus_device
      - delay: 5s
      - wait_until:
          condition:
            lambda: 'return !id(get_calibration);'
      - espnow.send:
          data: !lambda |-
            char buffer[30];
            snprintf(buffer, sizeof(buffer), "%s;humidity;%.1f", id(device_id).c_str(), id(humidity).state);
            return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
      - delay: 500ms
      - espnow.send:
          data: !lambda |-
            char buffer[30];
            snprintf(buffer, sizeof(buffer), "%s;temperature;%.1f", id(device_id).c_str(), id(temperature).state);
            return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
      - delay: 500ms
      - espnow.send:
          data: !lambda |-
            char buffer[30];
            snprintf(buffer, sizeof(buffer), "%s;conductivity;%.0f", id(device_id).c_str(), id(conductivity).state);
            return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
      - delay: 500ms
      - espnow.send:
          data: !lambda |-
            char buffer[30];
            snprintf(buffer, sizeof(buffer), "%s;ph;%.1f", id(device_id).c_str(), id(ph).state);
            return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
      - delay: 500ms
      - espnow.send:
          data: !lambda |-
            char buffer[30];
            snprintf(buffer, sizeof(buffer), "%s;nitrogen;%.0f", id(device_id).c_str(), id(nitrogen).state);
            return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
      - delay: 500ms
      - espnow.send:
          data: !lambda |-
            char buffer[30];
            snprintf(buffer, sizeof(buffer), "%s;phosphorus;%.0f", id(device_id).c_str(), id(phosphorus).state);
            return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
      - delay: 500ms
      - espnow.send:
          data: !lambda |-
            char buffer[30];
            snprintf(buffer, sizeof(buffer), "%s;potassium;%.0f", id(device_id).c_str(), id(potassium).state);
            return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
      - delay: 500ms
      - espnow.send:
          data: !lambda |-
            char buffer[30];
            snprintf(buffer, sizeof(buffer), "%s;salinity;%.1f", id(device_id).c_str(), id(salinity).state);
            return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
      - delay: 500ms
      - espnow.send:
          data: !lambda |-
            char buffer[30];
            snprintf(buffer, sizeof(buffer), "%s;tds;%.1f", id(device_id).c_str(), id(tds).state);
            return std::vector<unsigned char>(buffer, buffer + strlen(buffer));
      # - delay: 500ms
      # - lambda: !lambda |-
      #     ESP_LOGI("main", "Humidity: %.1f %%, Temperature: %.1f °C, Conductivity: %.0f µS/cm, pH: %.1f, Nitrogen: %.0f mg/kg, Phosphorus: %.0f mg/kg, Potassium: %.0f mg/kg, Salinity: %.1f mg/L, TDS: %.1f mg/L", id(humidity).state, id(temperature).state, id(conductivity).state, id(ph).state, id(nitrogen).state, id(phosphorus).state, id(potassium).state, id(salinity).state, id(tds).state);
