# These substitutions allow the end user to override certain values
substitutions:
  name: "lum-iot-test2"
  friendly_name: "Project Template"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: 5.2.1
    platform_version: 6.6.0

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: false

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: LumenSoft.espnow-test
    version: "1.0"

# To be able to get logs from the device via serial and api.
logger:
  level: verbose

globals:
  - id: hub_address
    type: uint64_t
    initial_value: "0x0"
    restore_value: yes
  - id: channel
    type: uint8_t
    initial_value: "3"
    restore_value: false

espnow:
  auto_add_peer: true
  wifi_channel: 2
  predefined_peers:
    - mac_address: e8:6b:ea:24:22:04
      wifi_channel: 1
    - mac_address: e8:6b:ea:24:22:03
    - mac_address: e8:6b:ea:24:22:02
  on_receive:
    - logger.log:
        format: "Received from: %s = '%s' cmd: %d RSSI: %d"
        args:
          [
            packet.get_payload(),
            packet.get_peer_code().c_str(),
            packet.get_command(),
            packet.rssi,
          ]

interval:
  - interval: 30sec
    then:
      - espnow.channel.set: !lambda return id(channel);
      - lambda: |-
          id(channel) = id(channel)+1;
          if (id(channel) > 10) {
            id(channel) = 1;
          }
