esphome:
  name: esp32-modbus
  platform: ESP32
  board: esp32-c3-devkitm-1

logger:

wifi:
  ssid: !secret WiFi_ssid
  password: !secret WiFi_password

external_components:
  - source:
      type: git
      url: https://gitlab.com/mathgaming/ripnetuk-esphome-easynow.git
      ref: main
    refresh: never

api:
  password: !secret API_password

ota:
  - platform: esphome
    password: !secret OTA_password

uart:
  - id: intmodbus
    tx_pin: 21
    rx_pin: 20
    baud_rate: 4800
    stop_bits: 1
    data_bits: 8
    parity: NONE
    debug:
      direction: BOTH

modbus:
  flow_control_pin: GPIO1
  id: modbus1

modbus_controller:
  - id: modbus_device
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    update_interval: never  # Do not poll sensor automatically

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: 'Humidity'
    register_type: holding
    address: 0x00
    unit_of_measurement: '%RH'
    value_type: U_WORD
    id: 'humidity'

#When commented out, the sensor works fine
proxy_transmitter:
  id: my_proxy_transmitter
  espnow_channel: 11
  receiver_mac_address: !secret receiver_mac_address
  sensors:
    - sensor: 'humidity'
      proxy_id: 'soil_hum_proxy'

interval:
  - interval: 10s
    then:
      - component.update: modbus_device
      - delay: 5s
      - lambda: |-
          ESP_LOGI("main", "Sending sensor data");
          ESP_LOGI("main", "Humidity: %f %%RH", id(humidity).state);
      - proxy_transmitter.send  # When commented out, the sensor works fine
